### ISSUE TITLE
version 2.0 pull

### ISSUE THREAD

**Issue by tumpio** [Noitidart/MouseControl#1]
Hello, any change to get the v2.0 development out?

I would like to contribute to it as much as I could.

**Comment by Noitidart** [comment]
You gotta forgive my delay. I had a major breaktrhough. Solved the mouse watching of all buttons (not just the three standard) on OS X and Windows. Got the ctypes working from off the main thread.

Also solved the functionalization issue of the prefs panel, switched to angular.

This sucker is my target right now. v1.5 has been failing me so I'm getting kicked into gear to get this up and out.

**Comment by Noitidart** [comment]
Ok phew! Finally made some major progress.

Please try installing v2 now, the advanced mouse control is not there, like hold, multi click, and blocking events you expect not to happen. But you can edit configurations, record mouse on it, hit apply, and then it works. Please test if you can for me. :)

Before working on the advanced control/blocking events, I'm going to now shift gears to work on mouse monitoring on linux. :)

**Comment by tumpio** [comment]
This is awesome news! I will test it this week end!

**Comment by tumpio** [comment]
I installed it just a moment ago and I'm currently running it. The new preferences page looks very nice! All the settings seems to work and so does the export and import functionality. 

I'm running it on linux, so I think the mouse action recording doesn't work yet, at least it doesn't give any feedback, other than "ok mouse left" and "ok mouse over it" in browser console.

But this is way cooler than what I was expecting! :+1:  I was just hoping for cross platform compatibility :)

**Comment by Noitidart** [comment]
Ah yeah the Linux mouse stuff I'm working on right now as we speak :)

Thanks so much for the cooler then expected comment :D

Are you familiar with X11 on Linux? I'm trying to find a way to listen for mouse events and also block them. If you install the latest mousecontrol you'll see i createa window and any events over that window get logged in console, but i need this for system wide, or at least just firefox wide.

**Comment by tumpio** [comment]
Oh, I see that now. hmm I'm trying to test it but Firefox crashes after few clicks on the blank window when I have browser console opened.

**Comment by Noitidart** [comment]
Yeah its horribly in test mode right now on linux :p

**Comment by tumpio** [comment]
well, this gets printed out:

```
ev: XButtonEvent(5, ctypes.UInt64("9"), 0, Display.ptr(ctypes.UInt64("0x7fa649cf4000")), ctypes.UInt64("16777217"), ctypes.UInt64("1200"), ctypes.UInt64("0"), ctypes.UInt64("17509408"), 105, 199, 105, 228, 1040, 3, 1) MMSyncWorker.js:791:6
rez_XNextEvent: 0 MMSyncWorker.js:790:6
ev: XButtonEvent(4, ctypes.UInt64("9"), 0, Display.ptr(ctypes.UInt64("0x7fa649cf4000")), ctypes.UInt64("16777217"), ctypes.UInt64("1200"), ctypes.UInt64("0"), ctypes.UInt64("17509469"), 105, 199, 105, 228, 16, 1, 1) MMSyncWorker.js:791:6
rez_XNextEvent: 0 MMSyncWorker.js:790:6


XButtonEvent 5 is right click and 4 left click. Googling brought me to these:
http://menehune.opt.wfu.edu/Kokua/Irix_6.5.21_doc_cd/usr/share/Insight/library/SGI_bookshelves/SGI_Developer/books/XLib_PG/sgi_html/ch09.html
https://tronche.com/gui/x/xlib/events/keyboard-pointer/keyboard-pointer.html

**Comment by tumpio** [comment]
Something more.. no idea what, but contains related words :) 
https://tronche.com/gui/x/xlib/events/keyboard-pointer/keyboard-pointer.html

**Comment by tumpio** [comment]
Some more and a working example:
http://user.xmission.com/~georgeps/documentation/tutorials/forReview-3.html

**Comment by Noitidart** [comment]
Thanks so much @tumpio ! :) Those are great articles and help me understand a bit more. I need to try to make it not be limited within the msg window created, and also need to figure out how to block events :(

**Comment by tumpio** [comment]
http://stackoverflow.com/questions/30238155/linux-x11-window-manager-blocking-mouse-events
http://stackoverflow.com/questions/3528304/xlib-getting-events-of-a-child-window?rq=1

Any help from these? How did you solve this on Mac?

**Comment by Noitidart** [comment]
Yep XGrabPointer is the direction I need to go. When I call it though it keeps failing with message `AlreadyGrabbed` which is so confusing.

On Mac a bunch of this, just searching stack and github source codes lol.

**Comment by Noitidart** [comment]
I got it working with `gdk_window_add_filter` however we want to avoid this, we want to use X. gdk uses X, do you have any ideas on how to find out what X functions `gdk_window_add_filter` is calling?

**Comment by tumpio** [comment]
Not really other than trying to look them from the source:
https://root.cern.ch/doc/master/gdkwindow_8c_source.html#l00115

**Comment by Noitidart** [comment]
Oh dang that's real useful I was looking for something like that, I'll keep digging thanks man!

**Comment by Noitidart** [comment]
Hi @carlin-q-scott by any chance would you know how to monitor the mouse events from another thread (ChromeWorker)? As you did for keys in Media Keys?

**Comment by Noitidart** [comment]
Alright @tumpio I gave up on the thread method, I tried for a month, I tried GTK, X11, and XCB (layero on of x11), but none of them work from another thread. Everyone kept telling me to go mainthread but I was sturbborn I wanted to match the Windows and OS X method, to be able monitor from another thread. Anyways it didn't work out so I am forced to settle on mainthread for Linux.

So with rev54 and rev55 - https://github.com/Noitidart/MouseControl/commit/f5b23d20c19871ee9312ffd2ee8c05b99a16c599 - I landed ability to track mouse. So you can now try opening up options and try recording. It should work.

I wasn't able to test horizontal wheel, if you have a horizontal wheel please test.

I haven't hooked up the trigger function, when matching mouse combintation is found yet for Linux, will work on that now.

**Comment by carlin-q-scott** [comment]
@Noitidart sorry I couldn't help with this. My add-on uses an interface specific to media playback in Linux so there's no overlap with mouse tracking.

**Comment by Noitidart** [comment]
Ah, thanks @carlin-q-scott really appreciate your input!

**Comment by tumpio** [comment]
@Noitidart I tried it now. I'm not sure if the recording works for me, at least I can't trigger anything.

Here is a browser log when opening MouseControl options:
https://gist.github.com/tumpio/f21c5c75c18ea18f87b2

and a log when trying mouse recording:
https://gist.github.com/tumpio/ea1d39d5a0425c26d669

**Comment by Noitidart** [comment]
@tumpio thanks for that test and the detaield logs.

Can you try to - open addon manager - uninstall the old version - close the addon manager tab - install the addon - then try please?

The GitHubExtensionInstaller addon doesnt work anymore as GitHub updated their layout, so I had to manually make it an xpi like this:

Here is a youtube vid of me trying it out:

https://www.youtube.com/watch?v=y8lcw3dUO1Q


What is your linux distro details by the way?

**Comment by Noitidart** [comment]
Hey @tumpio did you get a chance to test out fresh install from github? I was just hoping for some confidence that it does work for sure on Linux by your tests. If it doesnt work then Ill get to debugging :)

**Comment by tumpio** [comment]
@Noitidart sorry.  I tested it now again. I found out that it works on the current Firefox but not in Firefox developer edition / aurora.

**Comment by Noitidart** [comment]
Whoa no way thanks for that awesome testing! Ill look into that!

**Comment by Noitidart** [comment]
Hey @tumpio I finalllly fixed it I think. I tested it in Fx45 and the old way worked, but then I tested in Fx48 and it didn't work. It seems in Fx48 I have to use gdk3 instead of gdk2. So I made it test firefox version. If it's greater then 45 then it uses gdk3. Can you please test out the latest commit.

The about page is broken right now due to a change - https://bugzilla.mozilla.org/show_bug.cgi?id=1254752#c42

But the logging to the console of the mouse buttons should work in 46 and 47 if you could test whichever version you have that would be so cool!

Thanks man!

Also it's usable for basic mouse combintations, down/up/click (multi/dbl click and holding doesnt work yet)

**Comment by Noitidart** [comment]
Tested it in Fx46 and 47 it works :) thank god! that was a doozy i didnt realize what the heck was going on

**Comment by Noitidart** [comment]
Alriiiighty finally check it out v2.0a.rev117 is working as expected. Default configurations aren't set up. If you have old config then make sure to hit "Restore Defaults". :)

**Comment by Noitidart** [comment]
When I customize it to be exactly like MouseControl v1.5 defaults this my config screenshot:

![](http://i.imgur.com/bdC4xkF.png)

Can you please take a screenshot of your default config. I don't know if all Linux have the same B# it will help me setup the default buttons.

**Comment by Noitidart** [comment]
Uploaded alpha to the dev channel on AMO please check it out and share feedback :) - https://addons.mozilla.org/en-US/firefox/addon/mousecontrol/versions/beta

**Comment by tumpio** [comment]
Here is a screen shot, it is from Fedora linux:
![2016-04-03-052701_1366x768_scrot 1](https://cloud.githubusercontent.com/assets/6218382/14230386/08793664-f95d-11e5-9bf7-b8757d9521f6.png)

**Comment by tumpio** [comment]
> It seems in Fx48 I have to use gdk3 instead of gdk2. So I made it test firefox version. If it's greater then 45 then it uses gdk3.

Could you somehow check the active gdk version? I'm thinking if Linux distribution packagers can still choose to use gdk2 instead of gdk3 when Fx47-48 is released.

**Comment by tumpio** [comment]
> Uploaded alpha to the dev channel on AMO please check it out and share feedback :) - https://addons.mozilla.org/en-US/firefox/addon/mousecontrol/versions/beta

Great job! It is working well on the Firefox developer edition!

**Comment by tumpio** [comment]
Do you have to leave the area after doing a mouse combo? I'm trying to do two button combo but releasing it in the area resets it to the last button clicked.

hmm, would more than two button combos be useful? Like clicking multiple mouse buttons in right order to do a some action.

**Comment by tumpio** [comment]
Or maybe the combo creation could be done by dragging mouse icons that represent click actions in order to create a combo.

**Comment by Noitidart** [comment]
Thanks for that gtk2 gtk3 bug and info! I'll investigate in that direction.

Yeah the recording is tricky. What is the exact combo you are trying to do? I can record a screencast on how to record it and share to youtube. I think the video will help others out there until we can create a more intuitive recording mechanism. I didn't like that drag and drop as people might drag and drop "unnatural" order combination. :(

**Comment by Noitidart** [comment]
Hey @tumpio I tried hard but I could not get v2.x approved publicly. So I have release it unlisted. I updated the public listing. And sent an update to MouseControl so it shows the prompt and tells them where to download v2.x

You can grab it here - https://github.com/Noitidart/MouseControl/releases/tag/v2.0-unlisted

Here is the prompt given in the update:
![](http://i.imgur.com/48Ql9CB.png)

Here is the notes on the public listing:

![](http://i.imgur.com/N7L05Y6.png)

**Comment by tumpio** [comment]
@Noitidart  sorry for the late reply as usual. I have used the new 2.0 version about a week now on my work machine where I have Fedora Linux installed. It has been working very well and most importantly the issues with the right click context menu is gone for good! :+1: 

You have worked very hard for this and shown big love to your users! I would like to make a donation to show up my gratitude. Do you have a paypal account?

Some thought about the new version:
- I also didn't like much about the "forced" update. It was just bit unexpected behavior for an addon. Maybe just a notice "Please Update" would have been better in my opinion. But it's not big deal since I wanted to update anyway :)
- If Mozilla is not going to allow the usage of eval, I was thinking that how about creating a framework for command library add-ons that can add new commands and actions to MouseControl. There could be a skeleton add-on that users can use to create new methods and share these addons in AMO. What do you think about this idea?

I think this Issue can be now closed! Thanks again! :)

**Comment by Noitidart** [comment]
> @Noitidart sorry for the late reply as usual. I have used the new 2.0 version about a week now on my work machine where I have Fedora Linux installed. It has been working very well and most importantly the issues with the right click context menu is gone for good! 👍

Yahoo!!!

> You have worked very hard for this and shown big love to your users! I would like to make a donation to show up my gratitude. Do you have a paypal account?

You have done sooo much for me, motivating me, and getting me this far. You even tried to do development. You definitely did testing. I can't take from you, you really really helped me. Thank you so much for this thoughts!

> - I also didn't like much about the "forced" update. It was just bit unexpected behavior for an addon. Maybe just a notice "Please Update" would have been better in my opinion. But it's not big deal since I wanted to update anyway :)

v1.x is causing major issues on e10s :( It is even blocking e10s update. Indepdnent of e10s, it has major issues with the zoom functionality, I was overiding the global zoom behavior. AMO really wanted me to get people off it. :( 

> -   If Mozilla is not going to allow the usage of eval, I was thinking that how about creating a framework for command library add-ons that can add new commands and actions to MouseControl. There could be a skeleton add-on that users can use to create new methods and share these addons in AMO. What do you think about this idea?

I'm trying to re-write this as a webextension, I'm working on the learning C++ as native messaging will have to be used. I am just writing up a Linux exe and then I should be able o get started. With that though they will allow eval and `chrome.tabs.executeScript` which is eval in sandbox :) I hope to set up repo and connect mousecontrol to it so people can browse and discover new community provided commands :)
