### ISSUE TITLE
mouse control release pop up (does not work in Firefox 40)

### ISSUE THREAD

**Issue by roroba** [Noitidart/MouseControl#10]
Hi,

I had old version of mouse control (and old firefox version: 40-0-2) but some pop up force to make an update to 2.0 version, lamentably i can not configurate my mouse with this version  like the old version, there is not an set-up choice!, i tried to fix this disable this plug in a lot of time.

**Comment by Noitidart** [comment]
I had to do a force because v1.x is holding back multiprocess updates and has other bugs :(

Let me take a screencast on how to customize and then send to you. What combination are you trying to setup?

**Comment by roroba** [comment]
Here are my steeps to try to install mousecontrol and my problem to try to set up the mouse..

![problem](https://cloud.githubusercontent.com/assets/23200544/19909204/e6f6cf86-a05c-11e6-951f-f74eb5e2e777.png)

**Comment by roroba** [comment]
finally i update my firefox version to v.49 and fix the problem!! 

;)

**Comment by Noitidart** [comment]
Thank you so much for this info! I will set the minimum version on it to be what I tested it in which is Firefox 45 I think.
