### ISSUE TITLE
Custom command: previous/next page

### ISSUE THREAD

**Issue by vijfde** [Noitidart/MouseControl#16]
I would like to have a custom command to go to the previous/next page in the history of the currently active tab. However, the following does not work for me:

Previous:
`{ exec() { let domwin = Services.wm.getMostRecentWindow('navigator:browser'); if (domwin) domwin.gBrowser.goBack(); } }`
Next:
`{ exec() { let domwin = Services.wm.getMostRecentWindow('navigator:browser'); if (domwin) domwin.gBrowser.goForward(); } }`

What exactly am I doing wrong?
The chosen mouse actions work for a different default command, so the problem should be in the code.
_Windows 10, Firefox 49.0.2
Installed v2.x from Github, but add-on list and about:mousecontrol say 2.0 ..._

**Comment by Noitidart** [comment]
Thanks for posting! Whoops my mistake. It should be `__exec__` not `exec`.

This works:

**Go Back in Tab History**

```
{
    __exec__() {
        let domwin = Services.wm.getMostRecentWindow('navigator:browser');
        if (domwin) domwin.gBrowser.goBack();
    }
}
```

**Go Forward in Tab History**

```
{
    __exec__() {
        let domwin = Services.wm.getMostRecentWindow('navigator:browser');
        if (domwin) domwin.gBrowser.goForward();
    }
}
```

**Comment by vijfde** [comment]
Thank you very much, works like a charm!
