### ISSUE TITLE
Tab switching by mouse wheel doesn't work properly in Ubuntu.

### ISSUE THREAD

**Issue by shihyuan** [Noitidart/MouseControl#3]
Tab switching by holding the right-click and then turning the mouse wheel doesn't work in Ubuntu.
The only exception is when right-clicking on a place where there isn't a right-click menu, for example in the empty space of the Add-ons Manager page.

It seems to me that this is because the right-click menu is handled differently in Firefox for Linux than in Windows?

**Comment by Noitidart** [comment]
Hey @shihyuan do you have any experience with X11 C API? We're trying to get it working on Linux (already got Windows and Mac) for version 2 over here: https://github.com/Noitidart/MouseControl/issues/1

Please chime in if you have any ideas. I'm hoping to release v2 by Nov 30.

**Comment by Noitidart** [comment]
FInally! @shihyuan please try v2.0a.rev117  I just tested it on Linux. You have to first go to about:mousecontrol and customize the features. I haven't shipped it with default yet. When I customize it to be exactly like MouseControl v1.5 defaults this my config screenshot:

![](http://i.imgur.com/bdC4xkF.png)

Can you please take a screenshot of your default config. I don't know if all Linux have the same B# it will help me setup the default buttons.

**Comment by Noitidart** [comment]
Uploaded alpha to the dev channel on AMO please check it out and share feedback :) - https://addons.mozilla.org/en-US/firefox/addon/mousecontrol/versions/beta

**Comment by Noitidart** [comment]
@shihyuan I released 2.0 and it should be working very well now. Please try it out.

**Comment by Noitidart** [comment]
eeeee
